### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by twotwotwo** [Snack-X/wasm-works#2]
I'm looking for a compact wasm implementation of just SHA-256 to use in an open-source project. This fits those requirements, but has no license attached. Could you give it any license so I can reuse it?

**Comment by twotwotwo** [comment]
(The use case is that I'm hashing lots of tiny values, so the overhead of the Web Crypto API makes wasm the fastest option.)

**Comment by Snack-X** [comment]
That's pretty cool! I've added MIT license as usual.
